# Generated by Django 4.0.3 on 2022-03-25 13:12

import computed_property.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exe_descricao', models.TextField(verbose_name='Descrição')),
                ('exe_criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('exe_alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('exe_user_alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                                            related_name='exe_user_alterado_por',
                                                            to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('exe_user_criado_por',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exe_user_criado_por',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
        ),
        migrations.CreateModel(
            name='ExercicioAlternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eal_descricao', models.CharField(max_length=300, verbose_name='Alternativa')),
                ('eal_eh_correta', models.BooleanField(default=False, verbose_name='Resposta correta?')),
                ('eal_criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('eal_alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('eal_exercicio',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercicio.exercicio',
                                   verbose_name='Exercício')),
                ('eal_user_alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                                            related_name='eal_user_alterado_por',
                                                            to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('eal_user_criado_por',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eal_user_criado_por',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
        ),
        migrations.CreateModel(
            name='UserEstatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ues_qtd_exercicios_respondidos',
                 computed_property.fields.ComputedCharField(compute_from='qtd_exercicios_respondidos', editable=False,
                                                            max_length=12,
                                                            verbose_name='Quantidade de exercícios respondidos')),
                ('ues_acertos', models.IntegerField(default=0, editable=False, verbose_name='Qtd de Acertos')),
                ('ues_erros', models.IntegerField(default=0, editable=False, verbose_name='Qtd de Erros')),
                ('ues_criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ues_alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('ues_user_alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                                            related_name='ues_user_alterado_por',
                                                            to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('ues_user_criado_por',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ues_user_criado_por',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
        ),
        migrations.CreateModel(
            name='ExercicioResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ere_eh_alternativa_correta',
                 models.BooleanField(default=False, editable=False, verbose_name='Está correto?')),
                ('ere_criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ere_alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('ere_exercicio',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercicio.exercicio',
                                   verbose_name='Exercício')),
                ('ere_exercicioalternativa',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercicio.exercicioalternativa',
                                   verbose_name='Alternativa Selecionada')),
                ('ere_user_alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                                            related_name='ere_user_alterado_por',
                                                            to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('ere_user_criado_por',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ere_user_criado_por',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
        ),
    ]
