# Generated by Django 4.0.3 on 2022-03-25 16:23

import computed_property.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userestatistica',
            name='ues_aproveitamento',
            field=computed_property.fields.ComputedCharField(compute_from='aproveitamento', default=0, editable=False,
                                                             max_length=12, verbose_name='Aproveitamento'),
        ),
        migrations.AddField(
            model_name='userestatistica',
            name='ues_qtd_exercicios_totais',
            field=computed_property.fields.ComputedCharField(compute_from='qtd_exercicios_totais', default=0,
                                                             editable=False, max_length=12,
                                                             verbose_name='Total de exercícios'),
        ),
        migrations.AlterField(
            model_name='exercicioresposta',
            name='ere_user_criado_por',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='ere_user_criado_por', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='userestatistica',
            name='ues_acertos',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total de Acertos'),
        ),
        migrations.AlterField(
            model_name='userestatistica',
            name='ues_erros',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total de Erros'),
        ),
        migrations.AlterField(
            model_name='userestatistica',
            name='ues_user_alterado_por',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='ues_user_alterado_por', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Alterado por'),
        ),
        migrations.AlterField(
            model_name='userestatistica',
            name='ues_user_criado_por',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='ues_user_criado_por', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Criado por'),
        ),
    ]
